spring:
  liquibase:
    enabled: true
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_SERVER}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
